swagger: '2.0'
info:
  version: "1.0.0"
  title: Swagger
produces:
  - application/json
  - application/xml
  - application/text
basePath: "/"
paths:
  /report_formats:
    get:
      operationId: main.report_formats
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Internal Server Error
        default:
          description: Unknown error 
  /report/{category}/{format_type}:
    get:
      operationId: main.create_report
      parameters:
        - name: category
          in: path
          required: true
          type: string
          description: Data for the report (unit, group, nomenclature, recipes)
        - name: format_type
          in: path
          required: true
          type: string
          description: Report form (CSV, JSON, MARKDOWN, RTF, XML)
      responses:
        200:
          description: OK
          schema:
            type: string
        400:
          description: Bad Request
        500:
          description: Internal Server Error
        default:
          description: Unknown error
