from enum import Enum


class EventType(Enum):
    DELETE_NOMENCLATURE = "DELETE_NOMENCLATURE"
    CHANGE_NOMENCLATURE = "CHANGE_NOMENCLATURE"
    CHANGE_NOMECLATURE_RECIPES = "CHANGE_NOMECLATURE_RECIPES"
    CHANGE_NOMECLATURE_TRANSACTIONS = "CHANGE_NOMECLATURE_TRANSACTIONS"
    
    CHANGE_RANGE = "CHANGE_RANGE"
    CHANGE_BLOCK_PERIOD = "CHANGE_BLOCK_PERIOD"
    
    SAVE_REPOSITY = "SAVE_REPOSITY"
    LOAD_REPOSITY = "LOAD_REPOSITY"
    
    CREATE_TRIAL_BALANCE_REPORT = "CREATE_TRIAL_BALANCE_REPORT"
    
    SAVE_SETTINGS = "SAVE_SETTINGS"
    
    LOGGER_DEBUG = "LOGGER_DEBUG"
    LOGGER_INFO = "LOGGER_INFO"
    LOGGER_WARNING = "LOGGER_WARNING"
    LOGGER_ERROR = "LOGGER_ERROR"
    LOGGER_CRITICAL = "LOGGER_CRITICAL"