from enum import Enum


class EventType(Enum):
    DELETE_NOMENCLATURE = "DELETE_NOMENCLATURE"
    CHANGE_NOMENCLATURE = "CHANGE_NOMENCLATURE"
    CHANGE_RANGE = "CHANGE_RANGE"
    CHANGE_BLOCK_PERIOD = "CHANGE_BLOCK_PERIOD"