from enum import Enum


class EventType(Enum):
    DELETE_NOMENCLATURE = "DELETE_NOMENCLATURE"
    CHANGE_NOMENCLATURE = "CHANGE_NOMENCLATURE"
    CHANGE_NOMECLATURE_RECIPES = "CHANGE_NOMECLATURE_RECIPES"
    CHANGE_NOMECLATURE_TRANSACTIONS = "CHANGE_NOMECLATURE_TRANSACTIONS"
    CHANGE_RANGE = "CHANGE_RANGE"
    CHANGE_BLOCK_PERIOD = "CHANGE_BLOCK_PERIOD"
    SAVE_REPOSITY = "SAVE_REPOSITY"
    LOAD_REPOSITY = "LOAD_REPOSITY"